version: '3.8'

services:
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: order
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - backend

  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    environment:
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  order-db-data:
  payment-db-data:

networks:
  backend: